import {Header} from "../components/header/header";
import Post from "../components/post/post";
import apiData from './../api/posts.json'
import Head from 'next/head'
import styles from './../../styles/Home.module.css'

export default function IdPost(props){
    const {id,title,content,img} = props.props[0]
    console.log(props)
    return(
        <div className={styles.container}>
            <Head>
                <title>{`TripJournal - ${title}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <main>
                <Post id={id} title={title} content={content} img={img} readmore={false} />
            </main>
        </div>
    )
}
export async function getStaticPaths() {
    
    const data = apiData.data
    const paths = data.map(d=>{
        return {params:{id:d.id}}
    })
    return {
        paths,
        fallback: false
    }
    
}
export async function getStaticProps({ params }) {
    const data = {props:apiData.data.filter(d=>{
        return d.id===params.id
    })}
  return {
    props: data
  }

}