import Header from "./components/header/header";
import Head from 'next/head'
import styles from './../styles/Contact.module.css'

export default function Contact(){
    return(
        <div className={styles.container}>
            <Head>
                <title>TripJournal - Contato</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <h2>Fale Conosco</h2>
                <form>
                    <fieldset>
                        <label for="nome">Nome</label>
                        <input type="text" name="nome" id="nome" placeholder="Insira aqui seu nome"/>
                    </fieldset>
                    <fieldset>
                        <label for="email">E-mail</label>
                        <input type="text" name="email" id="email" placeholder="Insira aqui seu email"/>
                    </fieldset>
                    <fieldset>
                        <label for="message">Mensagem</label>
                        <textarea name="message" id="message" rows="8"></textarea>
                    </fieldset>
                    <button type="button">Enviar</button>
                </form>
            </main>
        </div>
    )
} 