import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './components/header/header'
import Post from './components/post/post'
import apiData from './api/posts.json'
export default function Home(props) { 
  const renderPosts = () =>{
    return props.data.map(post=>{  
      const {title, content, img, id}  = post 
      return(<Post key={post.title} id={id} title={title} content={content} img={img} />)
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>TripJournal - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {
          renderPosts()
        }        
      </main>
    </div>
  )
}
export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const data = apiData
  console.log(data)
  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: data
  }
}
